# Generated by Django 5.2.7 on 2025-11-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode_app', '0002_auto_20251104_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='resultado_real',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='puntos',
        ),
    ]
