# Generated by Django 5.2.7 on 2025-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode_app', '0003_remove_partido_resultado_real_remove_tarjeta_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado_real',
            field=models.IntegerField(blank=True, choices=[(1, 'Local'), (2, 'Empate'), (3, 'Visitante')], null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
