# Generated by Django 5.2.7 on 2025-11-19 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode_app', '0004_partido_resultado_real_tarjeta_puntos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comprobantes/')),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode_app.tarjeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
