# Generated by Django 5.2.7 on 2025-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode_app', '0005_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='cierre_prode',
            field=models.DateTimeField(blank=True, help_text='Momento límite para crear y pagar tarjetas.', null=True),
        ),
        migrations.AddField(
            model_name='fecha',
            name='inicio_fecha',
            field=models.DateTimeField(blank=True, help_text='Hora real en que inicia el primer partido de esta fecha.', null=True),
        ),
    ]
