# Generated by Django 5.2.7 on 2025-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode_app', '0006_fecha_cierre_prode_fecha_inicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='cierre_prode',
            field=models.DateTimeField(blank=True, help_text='Límite para crear y pagar tarjetas.', null=True),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='inicio_fecha',
            field=models.DateTimeField(blank=True, help_text='Hora del primer partido. Se usa para cerrar creación y pago de tarjetas.', null=True),
        ),
    ]
