# Generated by Django 5.2.7 on 2025-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode_app', '0008_alter_fecha_cierre_prode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='cierre_prode',
            field=models.DateTimeField(blank=True, help_text='Límite para crear y pagar tarjetas.', null=True),
        ),
    ]
